apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: apm-server
  namespace: default
spec:
  version: 7.17.10-f1f67132-SNAPSHOT
  mode: fleet
  policyID: eck-apm-server
  kibanaRef:
    name: kibana
  fleetServerRef:
    name: fleet-server
  deployment:
    replicas: 1
    strategy:
      # Can be changed to "Replace" for extremely memory limited environments.
      type: "RollingUpdate"
    podTemplate:
      spec:
        containers:
        - name: agent
          resources:
            limits:
              cpu: 1
              memory: "2Gi"
            requests:
              cpu: 1
              memory: "1Gi"
        securityContext:
          runAsUser: 0
