apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: fleet-server
spec:
  version: 7.17.10-f1f67132-SNAPSHOT
  mode: fleet
  fleetServerEnabled: true
  elasticsearchRefs:
  - name:  elasticsearch
  kibanaRef:
    name: kibana
  deployment:
    replicas: 1
    podTemplate:
      spec:
        containers:
        - name: agent
          resources:
            limits:
              memory: "512Mi"
            requests:
              memory: "256Mi"
        securityContext:
          runAsUser: 0
