---
name: bump-elastic-stack-snapshot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * 1-5'

permissions:
  contents: read

jobs:
  bump-elastic-stack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: elastic/apm-pipeline-library/.github/actions/updatecli@current
        with:
          vaultUrl: ${{ secrets.VAULT_ADDR }}
          vaultRoleId: ${{ secrets.VAULT_ROLE_ID }}
          vaultSecretId: ${{ secrets.VAULT_SECRET_ID }}
          pipeline: ./.ci/bump-elastic-stack-snapshot.yml
          command: '--experimental apply'
        env:
          BRANCH: main
          GITHUB_ACTOR: ${{ github.actor }}
